package units

// bunVolume is the base unit name for volume
const bunVolume = "cubic metre"

// volumeFamily represents the collection of units of volume
var volumeFamily = &Family{
	baseUnitName: bunVolume,
	description:  "unit of volume",
	name:         Volume,
}

// VolumeNames maps names to units of volume
var volumeNames = map[string]Unit{
	// metric
	bunVolume: {
		0, 0, 1,
		volumeFamily,
		"m\u00B3", bunVolume, "cubic metres",
		"a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{
			"cubic-metre":  "hyphenated",
			"cubic-metres": "hyphenated, plural",
			"cubic metres": "plural",
			"cubic-meter":  "US spelling, hyphenated",
			"cubic-meters": "US spelling, hyphenated, plural",
			"cubic meter":  "US spelling",
			"cubic meters": "US spelling, plural",
		},
		"", "",
	},

	"yl": {
		0, 0, y * 1e-3,
		volumeFamily,
		"yl", "yoctolitre", "yoctolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"zl": {
		0, 0, z * 1e-3,
		volumeFamily,
		"zl", "zeptolitre", "zeptolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"al": {
		0, 0, a * 1e-3,
		volumeFamily,
		"al", "attolitre", "attolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"fl": {
		0, 0, f * 1e-3,
		volumeFamily,
		"fl", "femtolitre", "femtolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"pl": {
		0, 0, p * 1e-3,
		volumeFamily,
		"pl", "picolitre", "picolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"nl": {
		0, 0, n * 1e-3,
		volumeFamily,
		"nl", "nanolitre", "nanolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"ul": {
		0, 0, u * 1e-3,
		volumeFamily,
		"ul", "microlitre", "microlitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"ml": {
		0, 0, m * 1e-3,
		volumeFamily,
		"ml", "millilitre", "millilitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{
			"cc":                "abbreviation",
			"cubic-centimetre":  "hyphenated",
			"cubic-centimetres": "hyphenated, plural",
			"cubic centimetre":  "full name",
			"cubic centimetres": "full name, plural",
			"cubic-centimeter":  "full name, US spelling, hyphenated",
			"cubic-centimeters": "full name, US spelling, hyphenated, plural",
			"cubic centimeter":  "full name, US spelling",
			"cubic centimeters": "full name, US spelling, plural",

			"millilitre":  "full name",
			"millilitres": "full name, plural",
			"milliliter":  "full name, US spelling",
			"milliliters": "full name, US spelling, plural",
		},
		"", "",
	},
	"cl": {
		0, 0, c * 1e-3,
		volumeFamily,
		"cl", "centilitre", "centilitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"dl": {
		0, 0, d * 1e-3,
		volumeFamily,
		"dl", "decilitre", "decilitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"litre": {
		0, 0, 1e-3,
		volumeFamily,
		"l", "litre", "litres",
		"a metric measure of volume." +
			" It is not an SI unit but may be used alongside them",
		[]Tag{TagMetric},
		map[string]string{
			"l":      "abbreviation",
			"litres": "plural",
			"liter":  "US spelling",
			"liters": "US spelling, plural",
		},
		"", "",
	},
	"dal": {
		0, 0, da * 1e-3,
		volumeFamily,
		"dal", "decalitre", "decalitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"hl": {
		0, 0, h * 1e-3,
		volumeFamily,
		"hl", "hectolitre", "hectolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"kl": {
		0, 0, k * 1e-3,
		volumeFamily,
		"kl", "kilolitre", "kilolitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"Ml": {
		0, 0, _M * 1e-3,
		volumeFamily,
		"Ml", "megalitre", "megalitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"Gl": {
		0, 0, _G * 1e-3,
		volumeFamily,
		"Gl", "gigalitre", "gigalitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"Tl": {
		0, 0, _T * 1e-3,
		volumeFamily,
		"Tl", "teralitre", "teralitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{
			"cubic kilometre":  "",
			"cubic kilometres": "plural",
			"cubic-kilometre":  "hyphenated",
			"cubic-kilometres": "hyphenated, plural",
			"cubic-kilometer":  "US spelling, hyphenated",
			"cubic-kilometers": "US spelling, hyphenated, plural",
			"cubic kilometer":  "US spelling",
			"cubic kilometers": "US spelling, plural",
		},
		"", "",
	},
	"Pl": {
		0, 0, _P * 1e-3,
		volumeFamily,
		"Pl", "petalitre", "petalitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"El": {
		0, 0, _E * 1e-3,
		volumeFamily,
		"El", "exalitre", "exalitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"Zl": {
		0, 0, _Z * 1e-3,
		volumeFamily,
		"Zl", "zettalitre", "zettalitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},
	"Yl": {
		0, 0, _Y * 1e-3,
		volumeFamily,
		"Yl", "yottalitre", "yottalitres", "a metric measure of volume.",
		[]Tag{TagSI, TagMetric},
		map[string]string{},
		"", "",
	},

	// bottle
	"bottle-wine": {
		0, 0, bottleToCubicMetre,
		volumeFamily,
		"bottle", "bottle (wine)", "bottles (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade. Note that there is a now obsolete bottle size of" +
			" 70cl with corresponding multiples.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"magnum": {
		0, 0, bottleToCubicMetre * 2,
		volumeFamily,
		"Magnum", "Magnum (wine)", "Magnums (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"marie-jeanne": {
		0, 0, bottleToCubicMetre * 3,
		volumeFamily,
		"Marie Jeanne", "Marie Jeanne (wine)", "Marie Jeannes (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"tappit-hen": {
		0, 0, bottleToCubicMetre * 3,
		volumeFamily,
		"Tappit Hen", "Tappit Hen (port)", "Tappit Hens (port)",
		"a measure of volume typically used in the wine and spirits" +
			" trade. This is specifically for port. The name" +
			" derives from the shape of the bottle which is said to" +
			" resemble a hen.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"tregnum": {
		0, 0, bottleToCubicMetre * 3,
		volumeFamily,
		"Tregnum", "Tregnum (port)", "Tregnums (port)",
		"a measure of volume typically used in the wine and spirits" +
			" trade, specifically for port.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"jeroboam": {
		0, 0, bottleToCubicMetre * 4,
		volumeFamily,
		"Jeroboam", "Jeroboam (wine)", "Jeroboams (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"rehoboam": {
		0, 0, bottleToCubicMetre * 6,
		volumeFamily,
		"Rehoboam", "Rehoboam (wine)", "Rehoboams (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"methuselah": {
		0, 0, bottleToCubicMetre * 8,
		volumeFamily,
		"Methuselah", "Methuselah (wine)", "Methuselahs (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"salmanazar": {
		0, 0, bottleToCubicMetre * 12,
		volumeFamily,
		"Salmanazar", "Salmanazar (wine)", "Salmanazars (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"balthazar": {
		0, 0, bottleToCubicMetre * 16,
		volumeFamily,
		"Balthazar", "Balthazar (wine)", "Balthazars (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"nebuchadnezzar": {
		0, 0, bottleToCubicMetre * 20,
		volumeFamily,
		"Nebuchadnezzar", "Nebuchadnezzar (wine)", "Nebuchadnezzars (wine)",
		"a measure of volume typically used in the wine and spirits" +
			" trade.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},

	// Imperial / US
	"cubic inch": {
		0, 0, cubicInchToCubicMetre,
		volumeFamily,
		"in\u00B3", "cubic inch", "cubic inches",
		"an imperial measure of volume.",
		[]Tag{TagImperial, TagUScustomary},
		map[string]string{
			"cubic-inch":   "hyphenated",
			"cubic-inches": "hyphenated, plural",
			"cubic inches": "plural",
		},
		"", "",
	},
	"cubic foot": {
		0, 0, cubicFootToCubicMetre,
		volumeFamily,
		"ft\u00B3", "cubic foot", "cubic feet",
		"an imperial measure of volume.",
		[]Tag{TagImperial, TagUScustomary},
		map[string]string{
			"cubic-foot": "hyphenated",
			"cubic-feet": "hyphenated, plural",
			"cubic feet": "plural",
		},
		"", "",
	},
	"cubic yard": {
		0, 0, cubicYardToCubicMetre,
		volumeFamily,
		"yd\u00B3", "cubic yard", "cubic yards",
		"an imperial measure of volume.",
		[]Tag{TagImperial, TagUScustomary},
		map[string]string{
			"cubic-yard":  "hyphenated",
			"cubic-yards": "hyphenated, plural",
			"cubic yards": "plural",
		},
		"", "",
	},

	"perch (masonry)": {
		0, 0, 16.5 * 1.5 * 1 * cubicFootToCubicMetre,
		volumeFamily,
		"masonry perch", "masonry perch", "masonry perches",
		"a traditional measure of volume for stone and other" +
			" masonry. Note that this refers to the measure" +
			" for dressed stone, a masonry perch of brickwork" +
			" or rubble is a third smaller being one perch" +
			" long by one foot high by one foot wide." +
			" Note that a perch can also be a" +
			" measure of length or area.",
		[]Tag{TagHist},
		map[string]string{},
		"", "",
	},

	"minim": {
		0, 0, fluidOzToCubicMetre / 480,
		volumeFamily,
		"min", "minim", "minims",
		"an imperial measure of volume (an apothecaries' measure).",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},
	"fluid-scruple": {
		0, 0, fluidOzToCubicMetre / 24,
		volumeFamily,
		"fl s", "fluid scruple", "fluid scruples",
		"an imperial measure of volume (an apothecaries' measure).",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},
	"fluid-drachm": {
		0, 0, fluidOzToCubicMetre / 8,
		volumeFamily,
		"fl dr", "fluid drachm", "fluid drachms",
		"an imperial measure of volume (an apothecaries' measure).",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},

	"fluid-ounce": {
		0, 0, fluidOzToCubicMetre,
		volumeFamily,
		"fl oz", "fluid ounce", "fluid ounces",
		"an imperial measure of volume.",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},
	"gill": {
		0, 0, fluidOzToCubicMetre * 5,
		volumeFamily,
		"gi", "gill", "gills",
		"an imperial measure of volume.",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},
	"pint": {
		0, 0, fluidOzToCubicMetre * 20,
		volumeFamily,
		"pt", "pint", "pints",
		"an imperial measure of volume. Note that this refers to" +
			" the British pint of 20 fluid ounces." +
			" See also the US pint.",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},
	"quart": {
		0, 0, fluidOzToCubicMetre * 40,
		volumeFamily,
		"qt", "quart", "quarts",
		"an imperial measure of volume.",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},
	"gallon": {
		0, 0, gallonToCubicMetre,
		volumeFamily,
		"gal", "gallon", "gallons",
		"an imperial measure of volume.",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},

	"pin": {
		0, 0, gallonToCubicMetre * 4.5,
		volumeFamily,
		"pin", "pin", "pins",
		"an imperial measure of volume, used in the brewing industry" +
			" for large quantities of beer.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"firkin": {
		0, 0, gallonToCubicMetre * 9,
		volumeFamily,
		"firkin", "firkin", "firkins",
		"an imperial measure of volume, used in the brewing industry" +
			" for large quantities of beer.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"kilderkin": {
		0, 0, gallonToCubicMetre * 18,
		volumeFamily,
		"kilderkin", "kilderkin", "kilderkins",
		"an imperial measure of volume, used in the brewing industry" +
			" for large quantities of beer.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"barrel": {
		0, 0, gallonToCubicMetre * 36,
		volumeFamily,
		"barrel", "barrel", "barrels",
		"an imperial measure of volume, used in the brewing industry" +
			" for large quantities of beer.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},
	"hogshead": {
		0, 0, gallonToCubicMetre * 54,
		volumeFamily,
		"hogshead", "hogshead", "hogsheads",
		"an imperial measure of volume, used in the brewing industry" +
			" for large quantities of beer.",
		[]Tag{TagDrinks},
		map[string]string{},
		"", "",
	},

	"peck": {
		0, 0, gallonToCubicMetre * 2,
		volumeFamily,
		"peck", "peck", "pecks",
		"an imperial measure of volume, typically for dry goods.",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},
	"bushel": {
		0, 0, gallonToCubicMetre * 8,
		volumeFamily,
		"bushel", "bushel", "bushels",
		"an imperial measure of volume, typically for dry goods.",
		[]Tag{TagImperial},
		map[string]string{},
		"", "",
	},

	"teaspoon": {
		0, 0, usFluidOzToCubicMetre * 0.5 / 3.0,
		volumeFamily,
		"tsp", "teaspoon", "teaspoons",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"tablespoon": {
		0, 0, usFluidOzToCubicMetre * 0.5,
		volumeFamily,
		"Tbsp", "tablespoon", "tablespoons",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-fluid-ounce": {
		0, 0, usFluidOzToCubicMetre,
		volumeFamily,
		"US fl oz", "US fluid ounce", "US fluid ounces",
		"The US fluid ounce is defined as 1/128 of a US gallon" +
			" which is based on the wine gallon of 231 cubic inches" +
			" which was used in the UK prior to the adoption of" +
			" the imperial system after 1824.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-shot": {
		0, 0, usFluidOzToCubicMetre * 1.5,
		volumeFamily,
		"shot", "US shot", "US shots",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-gill": {
		0, 0, usFluidOzToCubicMetre * 4,
		volumeFamily,
		"US gi", "US gill", "US gills",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-cup": {
		0, 0, usFluidOzToCubicMetre * 8,
		volumeFamily,
		"US cp", "US cup", "US cups",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{
			"cup":  "",
			"cups": "plural",
		},
		"", "",
	},
	"US-pint": {
		0, 0, usFluidOzToCubicMetre * 16,
		volumeFamily,
		"US pt", "US pint", "US pints",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-quart": {
		0, 0, usFluidOzToCubicMetre * 32,
		volumeFamily,
		"US qt", "US quart", "US quarts",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-gallon": {
		0, 0, usFluidOzToCubicMetre * 128,
		volumeFamily,
		"US gal", "US gallon", "US gallons",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{
			"US-wet-gallon": "",
			"US gallon":     "",
		},
		"", "",
	},
	"barrel-oil": {
		0, 0, usFluidOzToCubicMetre * 128 * 42,
		volumeFamily,
		"bbl(oil)", "oil barrel", "oil barrels",
		"a US Customary measure of volume.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-dry-gallon": {
		0, 0, usDryGallonToCubicMetre,
		volumeFamily,
		"US dry gal", "US dry gallon", "US dry gallons",
		"a US Customary measure of volume, typically for dry goods.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-bushel": {
		0, 0, usDryGallonToCubicMetre * 8,
		volumeFamily,
		"US bushel", "US bushel", "US bushels",
		"a US Customary measure of volume, typically for dry goods.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"US-dry-pint": {
		0, 0, usDryGallonToCubicMetre * 0.125,
		volumeFamily,
		"US dry pint", "US dry pint", "US dry pints",
		"a US Customary measure of volume, typically for dry goods.",
		[]Tag{TagUScustomary},
		map[string]string{},
		"", "",
	},
	"wine-gallon": {
		0, 0, cubicInchToCubicMetre * 231,
		volumeFamily,
		"wine gallon", "wine gallon", "wine gallons",
		"a  measure of volume in the UK, customarily from the 16th century" +
			" and by law since 1707 during the reign of Queen Anne." +
			" It is of interest principally because" +
			" it is the basis of US fluid measures",
		[]Tag{TagHist},
		map[string]string{},
		"", "",
	},

	// Colloquial
	"20ft shipping container": {
		0, 0, 33.14,
		volumeFamily,
		"vol. of a TEU",
		"volume of a 20ft shipping container",
		"volumes of a 20ft shipping container",
		"a colloquial term referencing the volume of a standard 20 foot" +
			" shipping container" +
			" presumably to give an impression of scale." +
			" The TEU abbreviation stands for Twenty foot Equivalent Unit.",
		[]Tag{TagColloquial},
		map[string]string{},
		"", "",
	},
}
